// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZFOEi4TXU4z4gssPfssSOx2NjBKiYjw0',
    appId: '1:311048959593:web:c3a9b67b92ff86c71c54f8',
    messagingSenderId: '311048959593',
    projectId: 'schoolvan-6d23a',
    authDomain: 'schoolvan-6d23a.firebaseapp.com',
    storageBucket: 'schoolvan-6d23a.firebasestorage.app',
    measurementId: 'G-6CL1TG3C9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1oJjzAG3B7yIHKmucE_sMiYHdEHZ__yk',
    appId: '1:311048959593:android:9b3857cd7291f2f31c54f8',
    messagingSenderId: '311048959593',
    projectId: 'schoolvan-6d23a',
    storageBucket: 'schoolvan-6d23a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsk-IuUKSr_RDCrWHtp_7JJ5JsqKA40do',
    appId: '1:311048959593:ios:a0b736a589b156bb1c54f8',
    messagingSenderId: '311048959593',
    projectId: 'schoolvan-6d23a',
    storageBucket: 'schoolvan-6d23a.firebasestorage.app',
    iosBundleId: 'com.example.alphonsatravels',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsk-IuUKSr_RDCrWHtp_7JJ5JsqKA40do',
    appId: '1:311048959593:ios:a0b736a589b156bb1c54f8',
    messagingSenderId: '311048959593',
    projectId: 'schoolvan-6d23a',
    storageBucket: 'schoolvan-6d23a.firebasestorage.app',
    iosBundleId: 'com.example.alphonsatravels',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZFOEi4TXU4z4gssPfssSOx2NjBKiYjw0',
    appId: '1:311048959593:web:8137f6eed54de1cc1c54f8',
    messagingSenderId: '311048959593',
    projectId: 'schoolvan-6d23a',
    authDomain: 'schoolvan-6d23a.firebaseapp.com',
    storageBucket: 'schoolvan-6d23a.firebasestorage.app',
    measurementId: 'G-8WJVCN75GM',
  );
}
